/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.amolga.mavenproject1.view;

import com.amolga.mavenproject1.model.Client;
import com.amolga.mavenproject1.model.Database;
import com.amolga.mavenproject1.model.Bill;
import com.amolga.mavenproject1.model.Table;
import com.amolga.mavenproject1.model.TableStatus;
import java.util.ArrayList;

/**
 *
 * @author sofia macedo
 */

public class InitialScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InitialScreen.class.getName());
    ArrayList<Client>  clients;
    private Client loggedClient;
    /**
     * Creates new form MainRestaurant
     */
    public InitialScreen(Client logged) {
        this.loggedClient = logged;
        initComponents();
        ((javax.swing.GroupLayout) jPanel2.getLayout()).setHonorsVisibility(bonusLabel, false);
        
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        configLoggedScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        restaurantText = new javax.swing.JLabel();
        bonusLabel = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        kitchen = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        restaurantText.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        restaurantText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restaurantText.setText("Amolga's An? Burguer");
        restaurantText.setToolTipText("");

        bonusLabel.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        bonusLabel.setForeground(new java.awt.Color(153, 0, 0));
        bonusLabel.setText("Bônus: R$ 0,00");

        menu.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        menu.setText("Menu");
        menu.setBorder(null);
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.setFocusPainted(false);
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
        });
        menu.addActionListener(this::menuActionPerformed);

        kitchen.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        kitchen.setText("Cozinha");
        kitchen.setBorder(null);
        kitchen.setBorderPainted(false);
        kitchen.setContentAreaFilled(false);
        kitchen.setFocusPainted(false);
        kitchen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kitchenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kitchenMouseExited(evt);
            }
        });
        kitchen.addActionListener(this::kitchenActionPerformed);

        login.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        login.setText("Login");
        login.setBorder(null);
        login.setBorderPainted(false);
        login.setContentAreaFilled(false);
        login.setFocusPainted(false);
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.addActionListener(this::loginActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(restaurantText, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(bonusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(restaurantText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bonusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabel1.setText("<html> O seu melhor amigo na hora da fome! <html>");
        jLabel1.setName(""); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Amolga.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1598, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1164, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configLoggedScreen() {
        if (this.loggedClient != null) {
            login.setText("Sair");
            bonusLabel.setText("Bônus: R$ " + String.format("%.2f", loggedClient.getBonus()).replace(".", ","));
            bonusLabel.setVisible(true);
        } else {
            bonusLabel.setVisible(false);
        }
    }
    
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        if (login.getText().equals("Sair")) {
            int close = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja deslogar?",
                "Deslogar",
                javax.swing.JOptionPane.YES_NO_OPTION
            );
            
            if (close == javax.swing.JOptionPane.YES_OPTION) {
                InitialScreen logOutScreen = new InitialScreen(null);
                logOutScreen.setVisible(true);
                
                this.dispose();
            }
            
        } else {
            Login loginScreen = new Login();
            loginScreen.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_loginActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        boolean loginUsuario = (this.loggedClient != null);
        
        if (loginUsuario) {
            Bill activeBill = Database.getActiveBillByClient(loggedClient);
            if (activeBill == null) {
                // Seleção de mesa
                ArrayList<String> freeTableOptions = new ArrayList<>();
                for (Table t : Database.getTables()) {
                    if (t.getStatus() == TableStatus.FREE) {
                        freeTableOptions.add("Mesa " + t.getNumber());
                    }
                }
                if (freeTableOptions.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Desculpe, todas as mesas estão ocupadas no momento.", "Sem Mesas Disponíveis", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
                String selectedStr = (String) javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Selecione uma mesa disponível:",
                    "Seleção de Mesa",
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null,
                    freeTableOptions.toArray(),
                    freeTableOptions.get(0)
                );
                if (selectedStr == null) return; // Cancelado
                int tableNum = Integer.parseInt(selectedStr.replace("Mesa ", ""));
                Table table = Database.occupyTable(tableNum);
                if (table != null) {
                    Bill bill = new Bill();
                    bill.setClient(loggedClient);
                    bill.setTable(table);
                    Database.addActiveBill(bill);
                    javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Mesa " + tableNum + " ocupada com sucesso!\nSua senha temporária de acesso é: " + table.getCode() + "\nPor favor, guarde esta senha para o pagamento.",
                        "Mesa Reservada",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                    );
                    
                    MenuScreen screenMenu = new MenuScreen(bill);
                    screenMenu.setVisible(true);
                    this.dispose();
                }
            } else {
                // Já possui mesa ativa
                Object[] options = {"Fazer Novo Pedido", "Pedir Conta / Pagar", "Voltar"};
                int choice = javax.swing.JOptionPane.showOptionDialog(
                    this,
                    "Mesa " + activeBill.getTable().getNumber() + " ativa.\nO que deseja fazer?",
                    "Menu da Mesa",
                    javax.swing.JOptionPane.YES_NO_CANCEL_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[0]
                );
                if (choice == javax.swing.JOptionPane.YES_OPTION) {
                    MenuScreen screenMenu = new MenuScreen(activeBill);
                    screenMenu.setVisible(true);
                    this.dispose();
                } else if (choice == javax.swing.JOptionPane.NO_OPTION) {
                    PaymentScreen paymentScreen = new PaymentScreen(activeBill);
                    paymentScreen.setVisible(true);
                }
            }
        } else {
            Object[] options = {"OK"};
            int resposta = javax.swing.JOptionPane.showOptionDialog(this,
                    "Faça o login antes de acessar o menu.",
                    "Acesso somente com login",
                    javax.swing.JOptionPane.DEFAULT_OPTION,
                    javax.swing.JOptionPane.WARNING_MESSAGE,
                    null,
                    options,
                    options[0]
            );
            
            if (resposta == javax.swing.JOptionPane.OK_OPTION){
                Login loginScreen = new Login();
                loginScreen.setVisible(true);
                this.dispose();
            }
        }   
    }//GEN-LAST:event_menuActionPerformed

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        menu.setBackground(new java.awt.Color(255, 255, 255)); 
        menu.setContentAreaFilled(true); 
    }//GEN-LAST:event_menuMouseEntered

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
        menu.setContentAreaFilled(false); 
    }//GEN-LAST:event_menuMouseExited

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setBackground(new java.awt.Color(255, 255, 255)); 
        login.setContentAreaFilled(true);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setContentAreaFilled(false);
    }//GEN-LAST:event_loginMouseExited

    private void kitchenActionPerformed(java.awt.event.ActionEvent evt) {
        KitchenScreen kitchenScreen = new KitchenScreen(loggedClient);
        kitchenScreen.setVisible(true);
        this.dispose();
    }

    private void kitchenMouseEntered(java.awt.event.MouseEvent evt) {
        kitchen.setBackground(new java.awt.Color(255, 255, 255));
        kitchen.setContentAreaFilled(true);
    }

    private void kitchenMouseExited(java.awt.event.MouseEvent evt) {
        kitchen.setContentAreaFilled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InitialScreen(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonusLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton kitchen;
    private javax.swing.JButton login;
    private javax.swing.JButton menu;
    private javax.swing.JLabel restaurantText;
    // End of variables declaration//GEN-END:variables
}
