/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.amolga.mavenproject1.view;

import com.amolga.mavenproject1.model.Client;
import java.util.ArrayList;

/**
 *
 * @author leticia
 */
public class Login extends javax.swing.JFrame {
    
    ArrayList<Client> clientes;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newAccount = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        passwordFieldLogin = new javax.swing.JPasswordField();
        textNameLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 328));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 360));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        newAccount.setText("Criar Conta");
        newAccount.addActionListener(this::newAccountActionPerformed);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Não tem uma conta ainda?");

        enterButton.setText("Entrar");
        enterButton.addActionListener(this::enterButtonActionPerformed);

        passwordFieldLogin.setText("Senha");
        passwordFieldLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldLoginFocusLost(evt);
            }
        });

        textNameLogin.setText("Nome");
        textNameLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textNameLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNameLoginFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(passwordFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newAccount)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterButton))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newAccount)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountActionPerformed
        Register registerScreen = new Register(); 
        registerScreen.setVisible(true); // Show the register screen
        this.dispose(); // Close the current login screen
    }//GEN-LAST:event_newAccountActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        String name = textNameLogin.getText();
        String password = passwordFieldLogin.getText();
        Client logged = null;
        
        for(Client c : clientes){
            if(c.getName().equals(name)){
                if(c.getPassword().equals(password)){
                    logged = c;
                    break;
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Senha incorreta", "Erro de Login", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void textNameLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNameLoginFocusGained
        if (textNameLogin.getText().equals("Nome")) {
        textNameLogin.setText("");
        textNameLogin.setForeground(java.awt.Color.BLACK); 
        }
    }//GEN-LAST:event_textNameLoginFocusGained

    private void textNameLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNameLoginFocusLost
        if (textNameLogin.getText().isEmpty()) {
        textNameLogin.setForeground(java.awt.Color.GRAY); 
        textNameLogin.setText("Nome");
        }
    }//GEN-LAST:event_textNameLoginFocusLost

    private void passwordFieldLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldLoginFocusGained
        if (String.valueOf(passwordFieldLogin.getPassword()).equals("Senha")) {
            passwordFieldLogin.setText("");
            passwordFieldLogin.setForeground(java.awt.Color.BLACK); 
            passwordFieldLogin.setEchoChar('•'); 
        }
    }//GEN-LAST:event_passwordFieldLoginFocusGained

    private void passwordFieldLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldLoginFocusLost
        if (String.valueOf(passwordFieldLogin.getPassword()).isEmpty()) {
            passwordFieldLogin.setForeground(java.awt.Color.GRAY); 
            passwordFieldLogin.setText("Senha");
            passwordFieldLogin.setEchoChar((char) 0); 
        }
    }//GEN-LAST:event_passwordFieldLoginFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton newAccount;
    private javax.swing.JPasswordField passwordFieldLogin;
    private javax.swing.JTextField textNameLogin;
    // End of variables declaration//GEN-END:variables
}
