package com.amolga.mavenproject1.view;

import com.amolga.mavenproject1.model.MenuItem;
import com.amolga.mavenproject1.model.Food;
import com.amolga.mavenproject1.model.Drink;
import com.amolga.mavenproject1.model.Database;
import com.amolga.mavenproject1.model.Client;
import java.util.List;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author enzoschubach
 */
public class MenuScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuScreen.class.getName());
    private final ArrayList<MenuItem> menuItems = new ArrayList<>();
    private Client loggedClient;
    private com.amolga.mavenproject1.model.Order currentOrder;
    
    /**
     * Creates new form MenuScreen
     */
    public MenuScreen() {
        this(null);
    }
    
    public MenuScreen(Client loggedClient) {
        this.loggedClient = loggedClient;
        this.currentOrder = new com.amolga.mavenproject1.model.Order();
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        this.menuItems.addAll(Database.getItems());
        populateMenu();
    }

    public void populateMenu() {
        javax.swing.JPanel gridPanel = new javax.swing.JPanel();
        // 2 columns, vertical/horizontal gap of 15px
        gridPanel.setLayout(new java.awt.GridLayout(0, 2, 15, 15));
        
        for (MenuItem item : menuItems) {
            gridPanel.add(new MenuItemPanel(item, currentOrder));
        }
        
        jScrollPane1.setViewportView(gridPanel);
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    }

    public ArrayList<MenuItem> getMenuItems() {
        return this.menuItems;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuList = new javax.swing.JList<>();
        jPanelBottom = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        rmvButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuLabel.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("Cardápio");
        menuLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 0, 50, 0));
        getContentPane().add(menuLabel, java.awt.BorderLayout.NORTH);

        menuList.setAutoscrolls(false);
        jScrollPane1.setViewportView(menuList);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 10));

        confirmButton.setBackground(new java.awt.Color(0, 153, 0));
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("CONFIRMAR");
        confirmButton.setPreferredSize(new java.awt.Dimension(180, 44));
        confirmButton.addActionListener(this::confirmButtonActionPerformed);
        jPanelBottom.add(confirmButton);

        cancelButton.setBackground(new java.awt.Color(153, 0, 0));
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("CANCELAR");
        cancelButton.setPreferredSize(new java.awt.Dimension(180, 44));
        cancelButton.addActionListener(this::cancelButtonActionPerformed);
        jPanelBottom.add(cancelButton);

        createButton.setBackground(new java.awt.Color(0, 102, 204));
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("CRIAR");
        createButton.setPreferredSize(new java.awt.Dimension(180, 44));
        createButton.addActionListener(this::createButtonActionPerformed);
        jPanelBottom.add(createButton);

        rmvButton.setBackground(new java.awt.Color(255, 102, 0));
        rmvButton.setForeground(new java.awt.Color(255, 255, 255));
        rmvButton.setText("REMOVER");
        rmvButton.setPreferredSize(new java.awt.Dimension(180, 44));
        rmvButton.addActionListener(this::rmvButtonActionPerformed);
        jPanelBottom.add(rmvButton);

        getContentPane().add(jPanelBottom, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        if (currentOrder == null || currentOrder.getItems().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, adicione itens ao pedido antes de confirmar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        com.amolga.mavenproject1.model.Bill bill = new com.amolga.mavenproject1.model.Bill();
        bill.setClient(loggedClient);
        bill.getOrders().add(currentOrder);
        
        PaymentScreen paymentScreen = new PaymentScreen(bill);
        paymentScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        InitialScreen initial = new InitialScreen(loggedClient);
        initial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        MenuItemCreation creationScreen = new MenuItemCreation(this);
        creationScreen.setVisible(true);
    }//GEN-LAST:event_createButtonActionPerformed

    private void rmvButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JPopupMenu popupMenu = new JPopupMenu();
        
        for (MenuItem item : menuItems) {
            JMenuItem jMenuItem = new JMenuItem(item.getName());
            jMenuItem.addActionListener(e -> {
                menuItems.remove(item);
                Database.removePItems(item);
                populateMenu();
                javax.swing.JOptionPane.showMessageDialog(this, "Item '" + item.getName() + "' removido com sucesso!", "Removido", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            });
            popupMenu.add(jMenuItem);
        }
        popupMenu.show(rmvButton, 0, rmvButton.getHeight());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton createButton;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JList<String> menuList;
    private javax.swing.JButton rmvButton;
    // End of variables declaration//GEN-END:variables
}
