/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.amolga.mavenproject1.view;

import com.amolga.mavenproject1.model.MenuItem;
import com.amolga.mavenproject1.model.Food;
import com.amolga.mavenproject1.model.Drink;

/**
 *
 * @author enzoschubach
 */
public class MenuItemPanel extends javax.swing.JPanel {
    
    private int actualQuantity;
    private MenuItem item;
    
    /**
     * Creates new form MenuItemPanel
     */
    public MenuItemPanel() {
        initComponents();
        actualQuantity = 0;
        setOpaque(false);
    }
    
    public MenuItemPanel(MenuItem item) {
        this();
        this.item = item;
        if (item != null) {
            menuItemLabel.setText(item.getName());
            if (item instanceof Food food) {
                supplierLabel.setText("");
                descriptionLabel.setText("<html><div style='text-align:center'>" + food.getDescription() + "</div></html>");
            } else if (item instanceof Drink drink) {
                supplierLabel.setText("<html><div style='text-align:center'>Fornecedor: " + drink.getSupplier() + "</div></html>");
                descriptionLabel.setText("");
            }
        }
    }

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
        
        // Background
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
        
        // Border
        g2.setColor(new java.awt.Color(220, 220, 220));
        g2.setStroke(new java.awt.BasicStroke(1.5f));
        g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);
        
        g2.dispose();
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        menuItemLabel = new javax.swing.JLabel();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        quantityLabel = new javax.swing.JLabel();
        supplierLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(243, 243, 243));

        menuItemLabel.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        menuItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuItemLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        plusButton.setBackground(new java.awt.Color(0, 153, 0));
        plusButton.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        plusButton.setForeground(new java.awt.Color(255, 255, 255));
        plusButton.setText("+");
        plusButton.addActionListener(this::plusButtonActionPerformed);

        minusButton.setBackground(new java.awt.Color(153, 0, 0));
        minusButton.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        minusButton.setForeground(new java.awt.Color(255, 255, 255));
        minusButton.setText("-");
        minusButton.addActionListener(this::minusButtonActionPerformed);

        quantityLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        quantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantityLabel.setText("0");

        supplierLabel.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        supplierLabel.setForeground(new java.awt.Color(102, 102, 102));
        supplierLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplierLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        descriptionLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(102, 102, 102));
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuItemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
            .addComponent(supplierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
            .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(menuItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        this.actualQuantity++;
        this.quantityLabel.setText(String.valueOf(this.actualQuantity));
//        order.addItem(item);
    }//GEN-LAST:event_plusButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        if(this.actualQuantity>0){ //prevents negative numbers
            this.actualQuantity--;
            this.quantityLabel.setText(String.valueOf(this.actualQuantity));
//            order.removeItem(item);
        }
    }//GEN-LAST:event_minusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel menuItemLabel;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel supplierLabel;
    // End of variables declaration//GEN-END:variables
}
