package com.amolga.mavenproject1.view;

import com.amolga.mavenproject1.model.MenuItem;
import com.amolga.mavenproject1.model.Food;
import com.amolga.mavenproject1.model.Drink;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author enzoschubach
 */
public class MenuItemCreation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuItemCreation.class.getName());
    private MenuScreen parentScreen;

    /**
     * Creates new form MenuItemCreation
     */
    public MenuItemCreation() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        // Default select Food
        foodOption.setSelected(true);
        updateEnabledFields();
    }

    public MenuItemCreation(MenuScreen parentScreen) {
        this();
        this.parentScreen = parentScreen;
    }

    private void updateEnabledFields() {
        if (foodOption.isSelected()) {
            descriptionBox.setEnabled(true);
            descriptionBox.setEditable(true);
            supplierField.setEnabled(false);
            supplierField.setText(""); // clear supplier
        } else if (drinkOption.isSelected()) {
            descriptionBox.setEnabled(false);
            descriptionBox.setText(""); // clear description
            supplierField.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        foodOption = new javax.swing.JRadioButton();
        drinkOption = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionBox = new javax.swing.JTextArea();
        nameField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        supplierField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        supplierLabel = new javax.swing.JLabel();
        priceField = new javax.swing.JFormattedTextField();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(foodOption);
        foodOption.setText("Comida");
        foodOption.addActionListener(this::foodOptionActionPerformed);

        buttonGroup1.add(drinkOption);
        drinkOption.setText("Bebida");
        drinkOption.addActionListener(this::drinkOptionActionPerformed);

        descriptionBox.setColumns(20);
        descriptionBox.setRows(5);
        jScrollPane1.setViewportView(descriptionBox);

        nameLabel.setText("Nome:");

        priceLabel.setText("Preço:");

        descriptionLabel.setText("Descrição:");

        supplierLabel.setText("Fornecedor(a):");

        priceField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        createButton.setBackground(new java.awt.Color(0, 153, 0));
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Criar");
        createButton.addActionListener(this::createButtonActionPerformed);

        cancelButton.setBackground(new java.awt.Color(153, 0, 0));
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(foodOption)
                        .addGap(18, 18, 18)
                        .addComponent(drinkOption))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameLabel)
                            .addComponent(jScrollPane1)
                            .addComponent(nameField)
                            .addComponent(priceLabel)
                            .addComponent(descriptionLabel)
                            .addComponent(supplierLabel)
                            .addComponent(supplierField)
                            .addComponent(priceField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodOption)
                    .addComponent(drinkOption))
                .addGap(18, 18, 18)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(priceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supplierLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void foodOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodOptionActionPerformed
        updateEnabledFields();
    }//GEN-LAST:event_foodOptionActionPerformed

    private void drinkOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkOptionActionPerformed
        updateEnabledFields();
    }//GEN-LAST:event_drinkOptionActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String name = nameField.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O nome do item é obrigatório.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double price = 0.0;
        try {
            // Se o usuário usou vírgula, trocamos por ponto
            String priceText = priceField.getText().replace(",", ".").trim();
            if (priceText.isEmpty()) {
                // Tenta ler do valor formatado ou direto se não tiver formatador ativo
                Object val = priceField.getValue();
                if (val instanceof Number) {
                    price = ((Number) val).doubleValue();
                } else {
                    JOptionPane.showMessageDialog(this, "O preço é obrigatório.", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                price = Double.parseDouble(priceText);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Insira um preço válido.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (price <= 0) {
            JOptionPane.showMessageDialog(this, "O preço deve ser maior que zero.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        ArrayList<MenuItem> menuItems = (parentScreen != null) ? parentScreen.getMenuItems() : new ArrayList<>();
        com.amolga.mavenproject1.model.Manager manager = new com.amolga.mavenproject1.model.Manager(menuItems);

        if (foodOption.isSelected()) {
            String desc = descriptionBox.getText().trim();
            if (desc.isEmpty()) {
                JOptionPane.showMessageDialog(this, "A descrição é obrigatória para comidas.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            manager.registerFood(name, price, desc);
        } else {
            String supplier = supplierField.getText().trim();
            if (supplier.isEmpty()) {
                JOptionPane.showMessageDialog(this, "O fornecedor é obrigatório para bebidas.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            manager.registerDrink(name, price, supplier);
        }

        if (parentScreen != null) {
            parentScreen.populateMenu();
        }

        JOptionPane.showMessageDialog(this, "Item criado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_createButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuItemCreation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextArea descriptionBox;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JRadioButton drinkOption;
    private javax.swing.JRadioButton foodOption;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JFormattedTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField supplierField;
    private javax.swing.JLabel supplierLabel;
    // End of variables declaration//GEN-END:variables
}
