/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.amolga.mavenproject1.view;

import com.amolga.mavenproject1.model.Client;

/**
 *
 * @author leticia
 */
public class Register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textName = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        textName1 = new javax.swing.JTextPane();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        textNameRegister = new javax.swing.JTextField();
        textCpfRegister = new javax.swing.JTextField();
        textEmailRegister = new javax.swing.JTextField();
        passwordConfirmation = new javax.swing.JPasswordField();
        passwordFieldRegister = new javax.swing.JPasswordField();

        jScrollPane1.setViewportView(textName);

        jScrollPane2.setViewportView(textName1);

        passwordField.setText("Senha");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro");

        registerButton.setText("Cadastrar");
        registerButton.addActionListener(this::registerButtonActionPerformed);

        textNameRegister.setText("Nome");
        textNameRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textNameRegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNameRegisterFocusLost(evt);
            }
        });
        textNameRegister.addActionListener(this::textNameRegisterActionPerformed);

        textCpfRegister.setText("CPF");
        textCpfRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textCpfRegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textCpfRegisterFocusLost(evt);
            }
        });
        textCpfRegister.addActionListener(this::textCpfRegisterActionPerformed);

        textEmailRegister.setText("Email");
        textEmailRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textEmailRegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textEmailRegisterFocusLost(evt);
            }
        });
        textEmailRegister.addActionListener(this::textEmailRegisterActionPerformed);

        passwordConfirmation.setText("Senha");
        passwordConfirmation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordConfirmationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordConfirmationFocusLost(evt);
            }
        });

        passwordFieldRegister.setText("Senha");
        passwordFieldRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldRegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldRegisterFocusLost(evt);
            }
        });
        passwordFieldRegister.addActionListener(this::passwordFieldRegisterActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButton)
                    .addComponent(textNameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCpfRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmailRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textNameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textCpfRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textEmailRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(registerButton)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCpfRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCpfRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCpfRegisterActionPerformed

    private void textEmailRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailRegisterActionPerformed

    private void textNameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameRegisterActionPerformed
    
    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        if (String.valueOf(passwordField.getPassword()).equals("Senha")) {
            passwordField.setText("");
            passwordField.setForeground(java.awt.Color.BLACK); 
            passwordField.setEchoChar('•'); 
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if (String.valueOf(passwordField.getPassword()).isEmpty()) {
            passwordField.setForeground(java.awt.Color.GRAY); 
            passwordField.setText("Senha");
            passwordField.setEchoChar((char) 0); 
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    private void passwordConfirmationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordConfirmationFocusGained
        if (String.valueOf(passwordConfirmation.getPassword()).equals("Senha")) {
            passwordConfirmation.setText("");
            passwordConfirmation.setForeground(java.awt.Color.BLACK); 
            passwordConfirmation.setEchoChar('•'); 
        }
    }//GEN-LAST:event_passwordConfirmationFocusGained

    private void passwordConfirmationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordConfirmationFocusLost
        if (String.valueOf(passwordConfirmation.getPassword()).isEmpty()) {
            passwordConfirmation.setForeground(java.awt.Color.GRAY); 
            passwordConfirmation.setText("Senha");
            passwordConfirmation.setEchoChar((char) 0); 
        }
    }//GEN-LAST:event_passwordConfirmationFocusLost

    private void passwordFieldRegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldRegisterFocusGained
        if (String.valueOf(passwordFieldRegister.getPassword()).equals("Senha")) {
            passwordFieldRegister.setText("");
            passwordFieldRegister.setForeground(java.awt.Color.BLACK); 
            passwordFieldRegister.setEchoChar('•'); 
        }
    }//GEN-LAST:event_passwordFieldRegisterFocusGained

    private void passwordFieldRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldRegisterFocusLost
        if (String.valueOf(passwordFieldRegister.getPassword()).isEmpty()) {
            passwordFieldRegister.setForeground(java.awt.Color.GRAY);
            passwordFieldRegister.setText("Senha");
            passwordFieldRegister.setEchoChar((char) 0); 
        }
    }//GEN-LAST:event_passwordFieldRegisterFocusLost

    private void passwordFieldRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldRegisterActionPerformed

    private void textNameRegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNameRegisterFocusGained
        if (textNameRegister.getText().equals("Nome")) {
        textNameRegister.setText("");
        textNameRegister.setForeground(java.awt.Color.BLACK); 
        }
    }//GEN-LAST:event_textNameRegisterFocusGained

    private void textNameRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNameRegisterFocusLost
        if (textNameRegister.getText().isEmpty()) {
        textNameRegister.setForeground(java.awt.Color.GRAY);
        textNameRegister.setText("Nome");
        }
    }//GEN-LAST:event_textNameRegisterFocusLost

    private void textCpfRegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCpfRegisterFocusGained
        if (textCpfRegister.getText().equals("CPF")) {
        textCpfRegister.setText("");
        textCpfRegister.setForeground(java.awt.Color.BLACK); 
        }
    }//GEN-LAST:event_textCpfRegisterFocusGained

    private void textCpfRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCpfRegisterFocusLost
        if (textCpfRegister.getText().isEmpty()) {
        textCpfRegister.setForeground(java.awt.Color.GRAY);
        textCpfRegister.setText("CPF");
        }
    }//GEN-LAST:event_textCpfRegisterFocusLost

    private void textEmailRegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textEmailRegisterFocusGained
        if (textEmailRegister.getText().equals("Email")) {
        textEmailRegister.setText("");
        textEmailRegister.setForeground(java.awt.Color.BLACK); 
        }
    }//GEN-LAST:event_textEmailRegisterFocusGained

    private void textEmailRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textEmailRegisterFocusLost
        if (textEmailRegister.getText().isEmpty()) {
        textEmailRegister.setForeground(java.awt.Color.GRAY);
        textEmailRegister.setText("Email");
        }
    }//GEN-LAST:event_textEmailRegisterFocusLost

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        Client client = new Client(textNameRegister.getText(), textCpfRegister.getText(), textEmailRegister.getText(), passwordConfirmation.getText(), 0);
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPasswordField passwordConfirmation;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordFieldRegister;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField textCpfRegister;
    private javax.swing.JTextField textEmailRegister;
    private javax.swing.JTextPane textName;
    private javax.swing.JTextPane textName1;
    private javax.swing.JTextField textNameRegister;
    // End of variables declaration//GEN-END:variables
}
