/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.amolga.mavenproject1.view;

import com.amolga.mavenproject1.model.Client;
import com.amolga.mavenproject1.model.Database;

import com.amolga.mavenproject1.model.Database;
import java.util.ArrayList;

/**
 *
 * @author leticia
 */
public class Register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());
    private final ArrayList<Client> clients = new ArrayList<>();

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.clients.addAll(Database.getClients());
        
        textNameRegister.setForeground(java.awt.Color.GRAY);
        textNameRegister.setText("Nome");

        textEmailRegister.setForeground(java.awt.Color.GRAY);
        textEmailRegister.setText("exemplo@gmail.com");

        passwordFieldRegister.setEchoChar((char) 0);
        passwordFieldRegister.setForeground(java.awt.Color.GRAY);
        passwordFieldRegister.setText("*****");

        passwordConfirmation.setEchoChar((char) 0);
        passwordConfirmation.setForeground(java.awt.Color.GRAY);
        passwordConfirmation.setText("*****");

        textCpfRegister.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
        new javax.swing.JFormattedTextField.AbstractFormatter() {
            @Override
            public Object stringToValue(String text) { return text; }
            @Override
            public String valueToString(Object value) { return value == null ? "" : value.toString(); }
        }));
       textCpfRegister.setText("CPF");
       textCpfRegister.setForeground(java.awt.Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textName = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        textName1 = new javax.swing.JTextPane();
        passwordField = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        textNameRegister = new javax.swing.JTextField();
        textEmailRegister = new javax.swing.JTextField();
        passwordConfirmation = new javax.swing.JPasswordField();
        passwordFieldRegister = new javax.swing.JPasswordField();
        textCpfRegister = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(textName);

        jScrollPane2.setViewportView(textName1);

        passwordField.setText("Senha");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setAlignmentX(0.5F);
        jPanel1.setAlignmentY(0.5F);
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(1051, 591));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro");

        registerButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        registerButton.setText("Cadastrar");
        registerButton.addActionListener(this::registerButtonActionPerformed);

        textNameRegister.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        textNameRegister.setText("Nome");
        textNameRegister.setPreferredSize(new java.awt.Dimension(239, 34));
        textNameRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textNameRegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNameRegisterFocusLost(evt);
            }
        });
        textNameRegister.addActionListener(this::textNameRegisterActionPerformed);

        textEmailRegister.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        textEmailRegister.setText("Email");
        textEmailRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textEmailRegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textEmailRegisterFocusLost(evt);
            }
        });
        textEmailRegister.addActionListener(this::textEmailRegisterActionPerformed);

        passwordConfirmation.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        passwordConfirmation.setText("Confirmar Senha");
        passwordConfirmation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordConfirmationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordConfirmationFocusLost(evt);
            }
        });

        passwordFieldRegister.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        passwordFieldRegister.setText("Senha");
        passwordFieldRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldRegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldRegisterFocusLost(evt);
            }
        });
        passwordFieldRegister.addActionListener(this::passwordFieldRegisterActionPerformed);

        textCpfRegister.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        try {
            textCpfRegister.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        }
        catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textCpfRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textCpfRegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textCpfRegisterFocusLost(evt);
            }
        });
        textCpfRegister.addActionListener(this::textCpfRegisterActionPerformed);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel3.setText("Cpf");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel5.setText("Senha");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel6.setText("Confirmar senha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textNameRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(textCpfRegister)
                    .addComponent(textEmailRegister)
                    .addComponent(passwordFieldRegister)
                    .addComponent(passwordConfirmation)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 296, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(jLabel6)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCpfRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(textEmailRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textEmailRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailRegisterActionPerformed

    private void textNameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameRegisterActionPerformed
    
    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        if (String.valueOf(passwordField.getPassword()).equals("*****")) {
            passwordField.setText("");
            passwordField.setForeground(java.awt.Color.BLACK); 
            passwordField.setEchoChar('•'); 
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if (String.valueOf(passwordField.getPassword()).isEmpty()) {
            passwordField.setForeground(java.awt.Color.GRAY); 
            passwordField.setText("*****");
            passwordField.setEchoChar((char) 0); 
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    private void passwordConfirmationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordConfirmationFocusGained
        if (String.valueOf(passwordConfirmation.getPassword()).equals("*****")) {
            passwordConfirmation.setText("");
            passwordConfirmation.setForeground(java.awt.Color.BLACK); 
            passwordConfirmation.setEchoChar('•'); 
        }
    }//GEN-LAST:event_passwordConfirmationFocusGained

    private void passwordConfirmationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordConfirmationFocusLost
        if (String.valueOf(passwordConfirmation.getPassword()).isEmpty()) {
            passwordConfirmation.setForeground(java.awt.Color.GRAY); 
            passwordConfirmation.setText("*****");
            passwordConfirmation.setEchoChar((char) 0); 
        }
    }//GEN-LAST:event_passwordConfirmationFocusLost

    private void passwordFieldRegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldRegisterFocusGained
        if (String.valueOf(passwordFieldRegister.getPassword()).equals("*****")) {
            passwordFieldRegister.setText("");
            passwordFieldRegister.setForeground(java.awt.Color.BLACK); 
            passwordFieldRegister.setEchoChar('•'); 
        }
    }//GEN-LAST:event_passwordFieldRegisterFocusGained

    private void passwordFieldRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldRegisterFocusLost
        if (String.valueOf(passwordFieldRegister.getPassword()).isEmpty()) {
            passwordFieldRegister.setForeground(java.awt.Color.GRAY);
            passwordFieldRegister.setText("*****");
            passwordFieldRegister.setEchoChar((char) 0); 
        }
    }//GEN-LAST:event_passwordFieldRegisterFocusLost

    private void passwordFieldRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldRegisterActionPerformed

    private void textNameRegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNameRegisterFocusGained
        if (textNameRegister.getText().equals("Nome")) {
        textNameRegister.setText("");
        textNameRegister.setForeground(java.awt.Color.BLACK); 
        }
    }//GEN-LAST:event_textNameRegisterFocusGained

    private void textNameRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNameRegisterFocusLost
        if (textNameRegister.getText().isEmpty()) {
        textNameRegister.setForeground(java.awt.Color.GRAY);
        textNameRegister.setText("Nome");
        }
    }//GEN-LAST:event_textNameRegisterFocusLost

    private void textEmailRegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textEmailRegisterFocusGained
        if (textEmailRegister.getText().equals("exemplo@gmail.com")) {
        textEmailRegister.setText("");
        textEmailRegister.setForeground(java.awt.Color.BLACK); 
        }
    }//GEN-LAST:event_textEmailRegisterFocusGained

    private void textEmailRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textEmailRegisterFocusLost
        if (textEmailRegister.getText().isEmpty()) {
        textEmailRegister.setForeground(java.awt.Color.GRAY);
        textEmailRegister.setText("exemplo@gmail.com");
        }
    }//GEN-LAST:event_textEmailRegisterFocusLost

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String name = textNameRegister.getText().trim();
        String email = textEmailRegister.getText().trim();
        String cpf = textCpfRegister.getText().replaceAll("[^0-9]", "");
        String password = String.valueOf(passwordFieldRegister.getPassword());
        String pConfirmation = String.valueOf(passwordConfirmation.getPassword());

        boolean nameEmpty = name.isEmpty() || name.equals("Nome");
        boolean emailEmpty = email.isEmpty() || email.equals("Email");
        boolean cpfEmpty = cpf.isEmpty();
        boolean passwordEmpty = password.isEmpty() || password.equals("Senha");
        boolean pConfirmationEmpty = pConfirmation.isEmpty() || pConfirmation.equals("Confirmar Senha");

        if (nameEmpty || emailEmpty || cpfEmpty || passwordEmpty || pConfirmationEmpty) {
            javax.swing.JOptionPane.showMessageDialog(this,"Preencha todos os campos antes de cadastrar.","Campos incompletos",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cpf.length() != 11) {
            javax.swing.JOptionPane.showMessageDialog(this,"CPF inválido. Preencha todos os dígitos.","CPF incompleto",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!password.equals(pConfirmation)) {
            javax.swing.JOptionPane.showMessageDialog(this,"As senhas não coincidem.","Erro de confirmação",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        Client client = new Client(name, cpf, email, password, 0.0);
        Database.addClients(client);
        javax.swing.JOptionPane.showMessageDialog(this, "Conta criada com sucesso!", "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        InitialScreen mainScreen = new InitialScreen(client);
        mainScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerButtonActionPerformed

    private void textCpfRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCpfRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCpfRegisterActionPerformed

    private void textCpfRegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCpfRegisterFocusGained
        if (textCpfRegister.getForeground().equals(java.awt.Color.GRAY)) {
        textCpfRegister.setForeground(java.awt.Color.BLACK);
        try {
            javax.swing.text.MaskFormatter mask = new javax.swing.text.MaskFormatter("###.###.###-##");
            mask.setPlaceholderCharacter('_'); // <-- importante
            textCpfRegister.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mask));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textCpfRegister.setValue(null);
        }
    }//GEN-LAST:event_textCpfRegisterFocusGained

    private void textCpfRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCpfRegisterFocusLost
        String apenasDigitos = textCpfRegister.getText().replaceAll("[^0-9]", "");
        if (apenasDigitos.isEmpty()) {
            textCpfRegister.setForeground(java.awt.Color.GRAY);
            textCpfRegister.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                new javax.swing.JFormattedTextField.AbstractFormatter() {
                    @Override
                    public Object stringToValue(String text) { return text; }
                    @Override
                    public String valueToString(Object value) { return value == null ? "" : value.toString(); }
                }));
            textCpfRegister.setText("CPF");
        }
    }//GEN-LAST:event_textCpfRegisterFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPasswordField passwordConfirmation;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordFieldRegister;
    private javax.swing.JButton registerButton;
    private javax.swing.JFormattedTextField textCpfRegister;
    private javax.swing.JTextField textEmailRegister;
    private javax.swing.JTextPane textName;
    private javax.swing.JTextPane textName1;
    private javax.swing.JTextField textNameRegister;
    // End of variables declaration//GEN-END:variables
}
